version: "3"

services:
  # nginx-server:
  #   image: nginx
  #   container_name: tus_nginx_server
  #   working_dir: /apps
  #   volumes:
  #     - ./server/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ./server/logs/nginx:/var/log/nginx
  #     - ./server:/var/www/html
  #   ports:
  #     - "8080:80"
  #   environment:
  #     - REDIS_HOST=17.0.110.6
  #     - REDIS_PORT=6379
  #     - REDIS_DB=tus-php
  #   networks:
  #     tus-net:
  #       ipv4_address: 17.0.110.2

  # php-fpm-server:
  #   container_name: tus_php_fpm_server
  #   working_dir: /var/www/html
  #   build: .
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - ./server/php.ini:/usr/local/etc/php/php.ini
  #     - ./server:/var/www/html
  #   networks:
  #     tus-net:
  #       ipv4_address: 17.0.110.3
  #   command: sh /var/www/html/init.sh
  #   environment:
  #     - REDIS_HOST=17.0.110.6
  #     - REDIS_PORT=6379
  #     - REDIS_DB=tus-php


  nginx-client:
    image: nginx
    container_name: tus_nginx_client
    working_dir: /apps
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./client/logs/nginx:/var/log/nginx
      - ./client:/var/www/html
    ports:
      - "8085:80"
    networks:
      tus-net:
        ipv4_address: 17.0.110.4
  php-fpm-client:
    container_name: tus_php_fpm_client
    working_dir: /var/www/html
    build: .
    ports:
      - "9003:9000"
    volumes:
      - ./client/php.ini:/usr/local/etc/php/php.ini
      - ./client:/var/www/html
    networks:
      tus-net:
        ipv4_address: 17.0.110.5
    command: sh /var/www/html/init.sh

  # tus-redis-server:
  #   image: redis
  #   container_name: tus-redis-server
  #   volumes:
  #     - ./server/redis.conf:/etc/redis/redis.conf
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     tus-net:
  #       ipv4_address: 17.0.110.6
  #   environment:
  #     - REDIS_DATABASES=tus-php
  #     - REDIS_PORT=6379
networks:
  tus-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 17.0.110.0/26

